name: Vitest

on:
  push:

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run Vitest
        run: npm run test
